<?php
use \Drupal\Core\Entity\EntityInterface;


// function dummy_form_alter(&$form,\Drupal\Core\Form\FormStateInterface $form_state, $form_id){
//     if($form_id=='node_counternumber_edit_form'){
        
//         // kint($form);
//         // kint($form);
     
        
      
//         $word_count = str_word_count($form['body']['widget'][0]['#default_value']);
//         // $stripped = str_replace(' ', '', $word_count);
//         // $trim=trim($word_count);
       
//     $form['field_count']['widget'][0]['value']['#value'] = $word_count-2;
     
     




// }
// }

// function dummy_entity_presave(Drupal\Core\Entity\EntityInterface $entity){
//     if($entity->bundle()=="field_count"){
        
//         $body=$entity->get('body')->value;
//         $count = count(explode(" ", strip_tags(trim($body))));
         
//           $entity->set('field_count', $count);
// }
// }
// presave method

function dummy_node_presave($node) {
    $count = str_word_count($node->body->value);
    $node->field_count->value = $count - 2;
  }
