<?php 
// function apicall_theme($existing, $type, $theme, $path){
//   return[
//   $theme['mylist']=>[
//     'variables'=>['data' => []],
//   ],
// ];

// }

function apicall_theme($existing, $type, $theme, $path) {
  return[
      'mylists'=> [
          'template' => 'mylists',
          // 'path' => $path . '/templates',
          'variables' => [
              "data" => '',
          ],
      ],
  ];
}