<?php 
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;


function webform_form_alter(&$form, FormStateInterface $form_state, $form_id) {


if ($form_id == 'webform_submission_form') {
  $form['actions']['submit']['#submit'][] = 'event_submit_action';
  
}
}
function event_submit_action(&$form, FormStateInterface $form_state, $form_id){
  dpm($form_state);
  $node = Node::create([
    'type'        => 'log',
    'title'       => 'Druplicon test',
    // 'field_image' => [
    //   'target_id' => $file->id(),
    //   'alt' => 'Hello world',
    //   'title' => 'Goodbye world'
    // ],
  ]);
  $node->save();

}