<?php

/**
 * @file
 * Contains service.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function service_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the service module.
    case 'help.page.service':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function service_theme() {
  $theme = [];
  $theme['serviceentity'] = [
    'render element' => 'elements',
    'file' => 'serviceentity.page.inc',
    'template' => 'serviceentity',
  ];
  $theme['serviceentity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'serviceentity.page.inc',
  ];
  $theme['mylist']=[
    'variables'=>['title'=>'','desc'=>'', 'data' => [],],
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function service_theme_suggestions_serviceentity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#serviceentity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'serviceentity__' . $sanitized_view_mode;
  $suggestions[] = 'serviceentity__' . $entity->bundle();
  $suggestions[] = 'serviceentity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'serviceentity__' . $entity->id();
  $suggestions[] = 'serviceentity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
